repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args: ["protect", "--verbose", "--redact"]
  - repo: local
    hooks:
      - id: lint-if-available
        name: lint-if-available
        entry: node scripts/lint-if-available.js
        language: system
        pass_filenames: false

